# Generated by Django 4.0.6 on 2022-07-06 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('author', models.TextField()),
                ('publisher', models.TextField()),
                ('isbn', models.TextField()),
                ('itemWeight', models.PositiveIntegerField()),
                ('dimension', models.CharField(max_length=10)),
                ('pages', models.PositiveIntegerField()),
                ('language', models.TextField()),
                ('ratings', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
