# Generated by Django 4.0.6 on 2022-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='images',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
