# Generated by Django 4.0.6 on 2022-07-13 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_book_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='images',
            new_name='image',
        ),
    ]
